### ISSUE TITLE
[Rule Assistant] Window on non-existent monitor

### ISSUE THREAD

**Issue by SaraMeiSL** [rmlockwood/FLExTrans#886]
On a previous day, I had used RA on my laptop, but most likely on the external monitor, now when using RA on my laptop without an external monitor plugged in, RA is not visible as it is on that "non-existent monitor". (it is possible to get it back into view but it takes a number of keystrokes that the average user probably won't remember / be aware of). Is it possible to check how many monitors exist and then open RA to display on one that does exist (if previously used monitor no longer exists).
(NB I don't know if I had restarted my machine since last using FLExTrans; there is a possibility that I hadn't restarted, but I did re-open FLExTools.vbs)

**Comment by AndyBlack** [comment]
Fixed in version 1.0.0 at https://drive.google.com/file/d/1xm2KUSEQ7JMoFthWw3Y8JuFxUY5_jyYQ/view?usp=sharing

This also fixes an issue when the tool was minimized to the task bar and one closed it without re-opening it first.  In that case, it used to think the X,Y coordinates were -2333, -2333.  Now it remembers what they were before.

**Comment by AndyBlack** [comment]
I found a bug where if you had your second monitor to the left of your main monitor, it would not remember its position on the left monitor.  It's fixed at the same location: https://drive.google.com/file/d/1xm2KUSEQ7JMoFthWw3Y8JuFxUY5_jyYQ/view?usp=drive_link

**Comment by rmlockwood** [comment]
Sara can you test it? FLExTrans 3.12.3 build 383 has the new RA. You can verify the build number by looking at the file properties and details. It should show 3.12.3.383

**Comment by SaraMeiSL** [comment]
There is still a problem. I tested in my dev environment (3.13 plus yesterday's files from Github). 

I have laptop (screen 1) on the right of my external monitor (screen 2). Running Win 10 still. Screen 1 is the main display. 

When working with two screens, I move FT itself to screen 2, open RA, close RA, close FT. Unplug screen 2. Open FT (it opens on screen 1, the only screen), open RA - it opens "off screen". If I plug screen 2 back in at this stage I see the RA window; if I don't plug it in I have to use the numerous keystrokes to bring it back to screen 1.

When working I would use my screen 2 as my "working screen" as it is bigger than my laptop screen, but sometimes I take my laptop elsewhere and then work with only the laptop screen. Often I don't shut down, I just shut the lid. For me this scenario is likely to re-occur, but I don't know if it would for others.

**Comment by AndyBlack** [comment]
What is the version number for the RA you are testing?  It should be 1.0.0.  It works for me on my laptop/second monitor setup whether the second one is to the left or to the right.

**Comment by SaraMeiSL** [comment]
I've only got RA 0.30.3, but I have FLExTrans 3.13. @rmlockwood does this mean that the newer RA version isn't included in the Github repo that I'm using? 

![Image](https://github.com/user-attachments/assets/6ee0f7af-950f-48b1-8a4e-ba6e43c05839)

**Comment by AndyBlack** [comment]
@rmlockwood  The latest version of the RA installer is at https://drive.google.com/file/d/1xm2KUSEQ7JMoFthWw3Y8JuFxUY5_jyYQ/view?usp=drive_link

**Comment by rmlockwood** [comment]
@SaraMeiSL, it won't show up in your dev environment, it has to be installed separately or as part of the FT install. Use the above link from Andy, or install a recent FT version.

**Comment by SaraMeiSL** [comment]
@AndyBlack The issue with RA opening on the non-existent second monitor is fixed, but RA now always opens on display 1, and this is not necessarily the monitor that it was opened from. Is it possible that RA could open on the monitor that it was launched from?

**Comment by AndyBlack** [comment]
@SaraMeiSL If you move the RA from display 1 to display 2 and close it there on display 2, doesn't it open the next time on display 2?

**Comment by SaraMeiSL** [comment]
@AndyBlack PS other modules that open windows from FT - e.g. Sense Linker, Live Rule Tester - do open the window on the same display as FT, even with the situation I just described.

**Comment by rmlockwood** [comment]
@AndyBlack, the RA gets launched from a FLExTools module normally. Within that module I don't have any information about the FLExTools window.
Is it possible to search for the FLExTools window in the windows system and then get the position from that?

**Comment by AndyBlack** [comment]
@rmlockwood Maybe, but I'd need to know how to find it.  I did not see anything in the registry.
Could FT get its Windows X,Y coordinates and then set the registry values for RA?  Does https://stackoverflow.com/questions/7142342/get-window-position-size-with-python help with FT getting its window coordinates?

**Comment by AndyBlack** [comment]
@SaraMeiSL Try RA version 1.0.1 by downloading and running the new installer at https://drive.google.com/file/d/1JkgxrKYjEQKif2VXBa8jX1N0mMkyX5FQ/view?usp=sharing.  Running it should get you the new version.  You can check the Help / About ... to see if it's version 1.0.1.
When this version sees that the last place the RA was closed is no longer visible, it looks for a window whose title contains both "FLEXTools" and "FLExTrans", gets the X and Y coordinates of that window and tries using those for RA.  If it can't find such a window, it uses position (10, 10).

**Comment by SaraMeiSL** [comment]
@AndyBlack The behaviour of the RA is still different to the other modules that open further windows (eg LRT, SL). Both LRT and SL always open on the same window as FLExTrans (sorry for not being specific about that earlier). 

Since you can look for the window with title "FLExTools" and "FLExTrans" and use that for the position, can it always do that, rather than first looking to see where RA was last closed? Then RA would always open over FLExTrans, as LRT and SL do, and the number of displays wouldn't matter.

**Comment by AndyBlack** [comment]
@SaraMeiSL Yes, this should be possible.  @rmlockwood and @bbryson , do you agree that this is desirable?

**Comment by rmlockwood** [comment]
@AndyBlack , yes, I'm in favor of Sara's suggestion.

**Comment by AndyBlack** [comment]
Version 1.4.0 is at https://drive.google.com/file/d/1UPl7eYbfNcj-OXSDkpMHQel0IrYZeuZt/view?usp=sharing

**Comment by SaraMeiSL** [comment]
Monitor issues now fixed.
